#!/bin/sh
# pre-commit hook to add version info into the codebase (primarily for use in templates)

TARGET_FILE="internal/server/version/version.go"

# Get the current commit hash
COMMIT_HASH=$(git rev-parse --short HEAD)

# Get the current tag (if any)
TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "no-tag")

sed -i '' -E "s|^[[:space:]]*Commit[[:space:]]*=.*|    Commit = \"${COMMIT_HASH}\"|" "$TARGET_FILE"
sed -i '' -E "s|^[[:space:]]*Tag[[:space:]]*=.*|    Tag = \"${TAG}\"|" "$TARGET_FILE"

# Add updated files to the commit
git add $TARGET_FILE