MODULE_NAME := $(shell go list -m)

.DEFAULT_GOAL := build

.PHONY: fmt vet build

fmt:
	@echo "Running go fmt..."
	@go fmt ./...
	@go fmt ./cmd/scrape/...
	@go fmt ./cmd/scrape-server/...

vet: fmt
	@echo "Running go vet and staticcheck..."
	@go vet ./...
	@go vet ./cmd/scrape/...
	@go vet ./cmd/scrape-server/...
	@staticcheck ./...
	@staticcheck ./cmd/scrape/...
	@staticcheck ./cmd/scrape-server/...

build: vet
	@echo "Building $(MODULE_NAME)..."
	@go build -o bin/ ./cmd/scrape/... 
	@go build -o bin/ ./cmd/scrape-server/... 

clean:
	@echo "Cleaning $(MODULE_NAME)..."
	@rm -f bin/scrape*